# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Email-LocalDelivery
version:      0.08
version_from: LocalDelivery.pm
installdirs:  site
requires:
    Email::FolderType:             0.3
    Email::Simple:                 1.4
    File::Path::Expand:            0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
